# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""External Git revisions generated by ``config/update-external.py``.

Do not edit this file directly. Each revision comes from the corresponding
``config/external/<name>/uv.lock``.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ExternalDependency:
    """An external distribution installed from an immutable Git revision."""

    config_name: str
    distribution: str
    repository: str
    version: str
    commit: str
    runtime_requirements: tuple[str, ...]

    def requirement(self, extras: tuple[str, ...] = ()) -> str:
        """Return a PEP 508 requirement for this revision."""
        distribution = self.distribution
        if extras:
            distribution = f"{distribution}[{','.join(extras)}]"
        return f"{distribution} @ git+{self.repository}@{self.commit}"


EVALCHEMY = ExternalDependency(
    config_name="evalchemy",
    distribution="evalchemy",
    repository="https://github.com/marin-community/evalchemy.git",
    version="0.1.0",
    commit="cf66d0b14975379bf7fc5c4a7cfff1400c636f1c",
    runtime_requirements=(),
)

HARBOR = ExternalDependency(
    config_name="harbor",
    distribution="harbor",
    repository="https://github.com/marin-community/harbor.git",
    version="0.8.1",
    commit="725fc069555013da7ae7f895dd3658a2c2452d55",
    runtime_requirements=("daytona==0.200.2",),
)

MARIN_SKYRL = ExternalDependency(
    config_name="MarinSkyRL",
    distribution="skyrl",
    repository="https://github.com/marin-community/MarinSkyRL.git",
    version="0.1.0",
    commit="49fbef2dc2d83d626875801018f6f690992d5a1f",
    runtime_requirements=(),
)

EXTERNAL_DEPENDENCIES = (
    EVALCHEMY,
    HARBOR,
    MARIN_SKYRL,
)
